### ISSUE TITLE
Craft version 3 compatibility

### ISSUE THREAD

**Issue by mikestreety** [pixelandtonic/Anchors#2]
_I thought I would raise an issue for this so people can see it's being worked on._

Unless anyone beats me to it, i'm in the process of upgrading this plugin to work with v3 (as it's so great 😉 )

Progress can be found here: https://github.com/mikestreety/Anchors/tree/v3

Currently the author everywhere says me, but will update all the attribution to be Pixel and Tonic when ready to merge.

**Comment by mikestreety** [comment]
@brandonkelly @takobell 

Hey guys, iIve done the initial sweep of the code and have got it working on my version of Craft v3. Would you mind having a look over? Happy to make it into a pull request if that's easier to review.

https://github.com/mikestreety/Anchors/tree/v3

I'll update the namespace and URLs post-merge to pixel and tonic. Assuming the version would be bump to `2.0.0`.

**Comment by mikestreety** [comment]
I also know I need to update the readme back to what it was 👍

**Comment by takobell** [comment]
Could you do a pull request, @mikestreety? It's easier to review with a diff.

**Comment by mikestreety** [comment]
Of course.
